# .github/workflows/docker-publish.yml
name: Build and Push SAM2 Kubeflow Docker Image

# Controls when the action will run.
# Triggers the workflow on push events but only for the main/master branch,
# or when manually triggered (workflow_dispatch).
on:
  push:
    branches:
      - main # Adjust if your default branch is different (e.g., master)
    # Optionally, trigger on tag pushes for versioning
    # tags:
    #   - 'v*.*.*' # Trigger on tags like v1.0.0

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  build-and-push-to-dockerhub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a more recent version

      - name: Set up QEMU (for multi-platform builds - optional but good practice)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (enables more advanced build features)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # GitHub repository secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # GitHub repository secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of the repository
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Actually push the image to the registry
          tags: | # Define image tags
            ${{ secrets.DOCKERHUB_USERNAME }}/sam2-kubeflow-env:latest
            # You can add more tags, e.g., based on Git commit SHA or a version number
            # ${{ secrets.DOCKERHUB_USERNAME }}/sam2-kubeflow-env:${{ github.sha }}
            # If triggering on Git tags:
            # ${{ github.ref_type == 'tag' && format('{0}/{1}:{2}', secrets.DOCKERHUB_USERNAME, 'sam2-kubeflow-env', github.ref_name) || '' }}
          # Optional: Add build arguments, labels, cache settings etc.
          # labels: |
          #   org.opencontainers.image.source=${{ github.repositoryUrl }}
          #   org.opencontainers.image.revision=${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
